name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.results.outputs.version }}
      commit: ${{ steps.results.outputs.commit }}
    steps:
      - name: 'ðŸ“š Checkout'
        uses: actions/checkout@v2
      - name: get current commit hash
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: 'ðŸ§© Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@vegainvestments'
      - name: 'ðŸš€ Install pnpm'
        run: pnpm add -g pnpm
      - name: 'ðŸš€ Install packages'
        run: pnpm install
      - name: 'ðŸš€ Build'
        run: pnpm run-script build
      - name: 'ðŸš€ Publish'
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN}}
      - id: results
        run: |
          echo "::set-output name=version::$(jq -r .version ./package.json)"
          echo "::set-output name=commit::https://github.com/vegainvestments/${{ github.event.repository.name }}/commit/${{ env.commit_hash }}"
